openapi: 3.0.0
info:
  title: 'Ecommerce API - Users'
  version: '1.0.0'
paths:
  /users:
    get:
      tags:
        - Users
      summary: Obtener todos los usuarios
      description: Devuelve una lista de todos los usuarios.
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    idUser:
                      type: string
                      description: ID del usuario
                    client_name:
                      type: string
                      description: Nombre del cliente
                    phone:
                      type: string
                      description: Teléfono del cliente
                    email:
                      type: string
                      description: Correo electrónico del cliente
                    address:
                      type: string
                      description: Dirección del cliente
        '400':
          description: Solicitud inválida
        '404':
          description: Usuarios no encontrados
        '500':
          description: Error interno del servidor

  /users/{idUser}:
    get:
      tags:
        - Users
      summary: Obtener un usuario por ID
      description: Devuelve un usuario específico por su ID.
      parameters:
        - name: idUser
          in: path
          required: true
          description: ID del usuario a obtener
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  idUser:
                    type: string
                    description: ID del usuario
                  client_name:
                    type: string
                    description: Nombre del cliente
                  phone:
                    type: string
                    description: Teléfono del cliente
                  email:
                    type: string
                    description: Correo electrónico del cliente
                  address:
                    type: string
                    description: Dirección del cliente
        '400':
          description: Solicitud inválida
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

    patch:
      tags:
        - Users
      summary: Actualizar un usuario
      description: Permite actualizar la información de un usuario específico.
      parameters:
        - name: idUser
          in: path
          required: true
          description: ID del usuario a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_name:
                  type: string
                  description: Nombre del cliente
                phone:
                  type: string
                  description: Teléfono del cliente
                email:
                  type: string
                  description: Correo electrónico del cliente
                address:
                  type: string
                  description: Dirección del cliente
      responses:
        '200':
          description: Usuario actualizado con éxito
        '400':
          description: Solicitud inválida
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
